config/routes.rb
Designax::Application.routes.draw do

  match 'image_data/image/:id'  => 'image_data#show_image'
  match 'image_data/thumbnail/:id'  => 'image_data#show_thumbnail'
  match 'design_data/image/:id' => 'design_data#show_image'
  match 'design_data/thumb/:id' => 'design_data#show_thumbnail'
  match 'image_data/get_removeImages/:id' => 'image_data#get_removeImages'
  match 'image_data/get_firstfile/:id' => 'image_data#get_firstfile'
  match 'image_data/get_imagefiles/:id' => 'image_data#get_imagefiles'
  match 'image_data/get_currentId/:id' => 'image_data#get_currentId'

  resources :design_data
  resources :image_data

  devise_for :users, :path_prefix => 'd', :controllers => {
    :registrations => "users/registrations"
  }
  resources :users, only: [:index, :edit, :update, :destroy]
  
  resources :corp_states
  resources :states
  resources :user_infos
  resources :projects
  resources :user_projects

  root :to => 'design_data#index'
end

app/models/corp_state.rb
# encoding: utf-8

class CorpState < ActiveRecord::Base
  attr_accessible :state
end

app/controllers/corp_states_controller.rb
# -*- encoding: utf-8 -*-

class CorpStatesController < ApplicationController
  # GET /corp_states
  # GET /corp_states.json
  def index
    @corp_states = CorpState.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @corp_states }
    end
  end

  # GET /corp_states/1
  # GET /corp_states/1.json
  def show
    @corp_state = CorpState.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @corp_state }
    end
  end

  # GET /corp_states/new
  # GET /corp_states/new.json
  def new
    @corp_state = CorpState.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @corp_state }
    end
  end

  # GET /corp_states/1/edit
  def edit
    @corp_state = CorpState.find(params[:id])
  end

  # POST /corp_states
  # POST /corp_states.json
  def create
    @corp_state = CorpState.new(params[:corp_state])

    respond_to do |format|
      if @corp_state.save
        format.html { redirect_to @corp_state, notice: 'Corp state was successfully created.' }
        format.json { render json: @corp_state, status: :created, location: @corp_state }
      else
        format.html { render action: "new" }
        format.json { render json: @corp_state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /corp_states/1
  # PUT /corp_states/1.json
  def update
    @corp_state = CorpState.find(params[:id])

    respond_to do |format|
      if @corp_state.update_attributes(params[:corp_state])
        format.html { redirect_to @corp_state, notice: 'Corp state was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @corp_state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /corp_states/1
  # DELETE /corp_states/1.json
  def destroy
    @corp_state = CorpState.find(params[:id])
    @corp_state.destroy

    respond_to do |format|
      format.html { redirect_to corp_states_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/corp_states_helper.rb
module CorpStatesHelper
end

app/views/corp_states/_form.html.haml
= form_for @corp_state do |f|
  - if @corp_state.errors.any?
    #error_explanation
      %h2= "#{pluralize(@corp_state.errors.count, "error")} prohibited this corp_state from being saved:"
      %ul
        - @corp_state.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :state
    = f.text_field :state
  .actions
    = f.submit 'Save'

app/views/corp_states/edit.html.haml
%h1 Editing corp_state

= render 'form'

= link_to 'Show', @corp_state
\|
= link_to 'Back', corp_states_path

app/views/corp_states/index.html.haml
%h1 Listing corp_states

%table
  %tr
    %th State
    %th
    %th
    %th

  - @corp_states.each do |corp_state|
    %tr
      %td= corp_state.state
      %td= link_to 'Show', corp_state
      %td= link_to 'Edit', edit_corp_state_path(corp_state)
      %td= link_to 'Destroy', corp_state, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Corp state', new_corp_state_path

app/views/corp_states/new.html.haml
%h1 New corp_state

= render 'form'

= link_to 'Back', corp_states_path

app/views/corp_states/show.html.haml
%p#notice= notice

%p
  %b State:
  = @corp_state.state

= link_to 'Edit', edit_corp_state_path(@corp_state)
\|
= link_to 'Back', corp_states_path