config/routes.rb
Designax::Application.routes.draw do

  match 'image_data/image/:id'  => 'image_data#show_image'
  match 'image_data/thumbnail/:id'  => 'image_data#show_thumbnail'
  match 'design_data/image/:id' => 'design_data#show_image'
  match 'design_data/thumb/:id' => 'design_data#show_thumbnail'
  match 'image_data/get_removeImages/:id' => 'image_data#get_removeImages'
  match 'image_data/get_firstfile/:id' => 'image_data#get_firstfile'
  match 'image_data/get_imagefiles/:id' => 'image_data#get_imagefiles'
  match 'image_data/get_currentId/:id' => 'image_data#get_currentId'

  resources :design_data
  resources :image_data

  devise_for :users, :path_prefix => 'd', :controllers => {
    :registrations => "users/registrations"
  }
  resources :users, only: [:index, :edit, :update, :destroy]
  
  resources :corp_states
  resources :states
  resources :user_infos
  resources :projects
  resources :user_projects

  root :to => 'design_data#index'
end

app/models/user_info.rb
class UserInfo < ActiveRecord::Base
  attr_accessible :user_id
end

app/controllers/user_infos_controller.rb
# -*- encoding: utf-8 -*-

class UserInfosController < ApplicationController
  # GET /user_infos
  # GET /user_infos.json
  def index
    @user_infos = UserInfo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user_infos }
    end
  end

  # GET /user_infos/1
  # GET /user_infos/1.json
  def show
    @user_info = UserInfo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_info }
    end
  end

  # GET /user_infos/new
  # GET /user_infos/new.json
  def new
    @user_info = UserInfo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_info }
    end
  end

  # GET /user_infos/1/edit
  def edit
    @user_info = UserInfo.find(params[:id])
  end

  # POST /user_infos
  # POST /user_infos.json
  def create
    @user_info = UserInfo.new(params[:user_info])

    respond_to do |format|
      if @user_info.save
        format.html { redirect_to @user_info, notice: 'User info was successfully created.' }
        format.json { render json: @user_info, status: :created, location: @user_info }
      else
        format.html { render action: "new" }
        format.json { render json: @user_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_infos/1
  # PUT /user_infos/1.json
  def update
    @user_info = UserInfo.find(params[:id])

    respond_to do |format|
      if @user_info.update_attributes(params[:user_info])
        format.html { redirect_to @user_info, notice: 'User info was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_infos/1
  # DELETE /user_infos/1.json
  def destroy
    @user_info = UserInfo.find(params[:id])
    @user_info.destroy

    respond_to do |format|
      format.html { redirect_to user_infos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/user_infos_helper.rb
module UserInfosHelper
end

app/views/user_infos/_form.html.haml
= form_for @user_info do |f|
  - if @user_info.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user_info.errors.count, "error")} prohibited this user_info from being saved:"
      %ul
        - @user_info.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user_id
    = f.text_field :user_id
  .actions
    = f.submit 'Save'

app/views/user_infos/edit.html.haml
%h1 Editing user_info

= render 'form'

= link_to 'Show', @user_info
\|
= link_to 'Back', user_infos_path

app/views/user_infos/index.html.haml
%h1 Listing user_infos

%table
  %tr
    %th User
    %th
    %th
    %th

  - @user_infos.each do |user_info|
    %tr
      %td= user_info.user_id
      %td= link_to 'Show', user_info
      %td= link_to 'Edit', edit_user_info_path(user_info)
      %td= link_to 'Destroy', user_info, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User info', new_user_info_path

app/views/user_infos/new.html.haml
%h1 New user_info

= render 'form'

= link_to 'Back', user_infos_path

app/views/user_infos/show.html.haml
%p#notice= notice

%p
  %b User:
  = @user_info.user_id

= link_to 'Edit', edit_user_info_path(@user_info)
\|
= link_to 'Back', user_infos_path