config/routes.rb
Designax::Application.routes.draw do

  match 'image_data/image/:id'  => 'image_data#show_image'
  match 'image_data/thumbnail/:id'  => 'image_data#show_thumbnail'
  match 'design_data/image/:id' => 'design_data#show_image'
  match 'design_data/thumb/:id' => 'design_data#show_thumbnail'
  match 'image_data/get_removeImages/:id' => 'image_data#get_removeImages'
  match 'image_data/get_firstfile/:id' => 'image_data#get_firstfile'
  match 'image_data/get_imagefiles/:id' => 'image_data#get_imagefiles'
  match 'image_data/get_currentId/:id' => 'image_data#get_currentId'

  resources :design_data
  resources :image_data

  devise_for :users, :path_prefix => 'd', :controllers => {
    :registrations => "users/registrations"
  }
  resources :users, only: [:index, :edit, :update, :destroy]
  
  resources :corp_states
  resources :states
  resources :user_infos
  resources :projects
  resources :user_projects

  root :to => 'design_data#index'
end

app/models/state.rb
# encoding: utf-8

class State < ActiveRecord::Base
  attr_accessible :state
end

app/controllers/states_controller.rb
# -*- encoding: utf-8 -*-

class StatesController < ApplicationController
  # GET /states
  # GET /states.json
  def index
    @states = State.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @states }
    end
  end

  # GET /states/1
  # GET /states/1.json
  def show
    @state = State.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @state }
    end
  end

  # GET /states/new
  # GET /states/new.json
  def new
    @state = State.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @state }
    end
  end

  # GET /states/1/edit
  def edit
    @state = State.find(params[:id])
  end

  # POST /states
  # POST /states.json
  def create
    @state = State.new(params[:state])

    respond_to do |format|
      if @state.save
        format.html { redirect_to @state, notice: 'State was successfully created.' }
        format.json { render json: @state, status: :created, location: @state }
      else
        format.html { render action: "new" }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /states/1
  # PUT /states/1.json
  def update
    @state = State.find(params[:id])

    respond_to do |format|
      if @state.update_attributes(params[:state])
        format.html { redirect_to @state, notice: 'State was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1
  # DELETE /states/1.json
  def destroy
    @state = State.find(params[:id])
    @state.destroy

    respond_to do |format|
      format.html { redirect_to states_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/states/_form.html.haml
= form_for @state do |f|
  - if @state.errors.any?
    #error_explanation
      %h2= "#{pluralize(@state.errors.count, "error")} prohibited this state from being saved:"
      %ul
        - @state.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :state
    = f.text_field :state
  .actions
    = f.submit 'Save'

app/views/states/edit.html.haml
%h1 Editing state

= render 'form'

= link_to 'Show', @state
\|
= link_to 'Back', states_path

app/views/states/index.html.haml
# coding: utf-8

%h1 Listing states

%table
  %tr
    %th State
    %th
    %th
    %th

  - @states.each do |state|
    %tr
      %td= state.state
      %td= link_to 'Show', state
      %td= link_to 'Edit', edit_state_path(state)
      %td= link_to 'Destroy', state, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New State', new_state_path

app/views/states/new.html.haml
%h1 New state

= render 'form'

= link_to 'Back', states_path

app/views/states/show.html.haml
%p#notice= notice

%p
  %b State:
  = @state.state

= link_to 'Edit', edit_state_path(@state)
\|
= link_to 'Back', states_path