config/routes.rb
Designax::Application.routes.draw do

  match 'image_data/image/:id'  => 'image_data#show_image'
  match 'image_data/thumbnail/:id'  => 'image_data#show_thumbnail'
  match 'design_data/image/:id' => 'design_data#show_image'
  match 'design_data/thumb/:id' => 'design_data#show_thumbnail'
  match 'image_data/get_removeImages/:id' => 'image_data#get_removeImages'
  match 'image_data/get_firstfile/:id' => 'image_data#get_firstfile'
  match 'image_data/get_imagefiles/:id' => 'image_data#get_imagefiles'
  match 'image_data/get_currentId/:id' => 'image_data#get_currentId'

  resources :design_data
  resources :image_data

  devise_for :users, :path_prefix => 'd', :controllers => {
    :registrations => "users/registrations"
  }
  resources :users, only: [:index, :edit, :update, :destroy]
  
  resources :corp_states
  resources :states
  resources :user_infos
  resources :projects
  resources :user_projects

  root :to => 'design_data#index'
end

app/models/user_project.rb
class UserProject < ActiveRecord::Base
  attr_accessible :project_id, :user_id
end

app/controllers/user_projects_controller.rb
# -*- encoding: utf-8 -*-

class UserProjectsController < ApplicationController
  # GET /user_projects
  # GET /user_projects.json
  def index
    @user_projects = UserProject.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user_projects }
    end
  end

  # GET /user_projects/1
  # GET /user_projects/1.json
  def show
    @user_project = UserProject.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_project }
    end
  end

  # GET /user_projects/new
  # GET /user_projects/new.json
  def new
    @user_project = UserProject.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_project }
    end
  end

  # GET /user_projects/1/edit
  def edit
    @user_project = UserProject.find(params[:id])
  end

  # POST /user_projects
  # POST /user_projects.json
  def create
    @user_project = UserProject.new(params[:user_project])

    respond_to do |format|
      if @user_project.save
        format.html { redirect_to @user_project, notice: 'User project was successfully created.' }
        format.json { render json: @user_project, status: :created, location: @user_project }
      else
        format.html { render action: "new" }
        format.json { render json: @user_project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_projects/1
  # PUT /user_projects/1.json
  def update
    @user_project = UserProject.find(params[:id])

    respond_to do |format|
      if @user_project.update_attributes(params[:user_project])
        format.html { redirect_to @user_project, notice: 'User project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_projects/1
  # DELETE /user_projects/1.json
  def destroy
    @user_project = UserProject.find(params[:id])
    @user_project.destroy

    respond_to do |format|
      format.html { redirect_to user_projects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/user_projects_helper.rb
module UserProjectsHelper
end

app/views/user_projects/_form.html.haml
= form_for @user_project do |f|
  - if @user_project.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user_project.errors.count, "error")} prohibited this user_project from being saved:"
      %ul
        - @user_project.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :project_id
    = f.number_field :project_id
  .actions
    = f.submit 'Save'

app/views/user_projects/edit.html.haml
%h1 Editing user_project

= render 'form'

= link_to 'Show', @user_project
\|
= link_to 'Back', user_projects_path

app/views/user_projects/index.html.haml
%h1 Listing user_projects

%table
  %tr
    %th User
    %th Project
    %th
    %th
    %th

  - @user_projects.each do |user_project|
    %tr
      %td= user_project.user_id
      %td= user_project.project_id
      %td= link_to 'Show', user_project
      %td= link_to 'Edit', edit_user_project_path(user_project)
      %td= link_to 'Destroy', user_project, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User project', new_user_project_path

app/views/user_projects/new.html.haml
%h1 New user_project

= render 'form'

= link_to 'Back', user_projects_path

app/views/user_projects/show.html.haml
%p#notice= notice

%p
  %b User:
  = @user_project.user_id
%p
  %b Project:
  = @user_project.project_id

= link_to 'Edit', edit_user_project_path(@user_project)
\|
= link_to 'Back', user_projects_path